repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(client/|src/workato_platform/client/)
      - id: end-of-file-fixer
        exclude: ^(client/|src/workato_platform/client/)
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(client/|src/workato_platform/client/)
      - id: ruff-format
        exclude: ^(client/|src/workato_platform/client/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        args: [--explicit-package-bases]
        additional_dependencies:
          [
            types-requests,
            types-click,
            packaging,
            asyncclick>=8.0.0,
            pydantic>=2.11.7,
            dependency-injector>=4.41.0,
            inquirer>=3.1.0,
            aiohttp>=3.8.0,
            python-dateutil>=2.8.0,
            typing-extensions>=4.0.0,
            pytest>=7.0.0,
            pytest-asyncio>=0.21.0,
            pytest-mock>=3.10.0,
          ]
        exclude: ^(client/|src/workato_platform/client/)

  # pip-audit for dependency security auditing
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: [--format=json]

  # Local hooks for project-specific tasks
  - repo: local
    hooks:
      - id: generate-client
        name: Generate OpenAPI client
        entry: make generate-client
        language: system
        always_run: true
        pass_filenames: false
