library: asyncio
packageName: workato_platform_cli.client.workato_api
projectName: workato-platform-cli
packageVersion: 1.0.0
packageUrl: https://github.com/workato/workato-platform-cli
hideGenerationTimestamp: true
generateSourceCodeOnly: true
lazyImports: false
