# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.api_key_response import ApiKeyResponse

class TestApiKeyResponse(unittest.TestCase):
    """ApiKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyResponse:
        """Test ApiKeyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyResponse`
        """
        model = ApiKeyResponse()
        if include_optional:
            return ApiKeyResponse(
                data = workato_platform.client.workato_api.models.api_key.ApiKey(
                    id = 37326, 
                    name = 'Automation Inc.', 
                    auth_type = 'token', 
                    ip_allow_list = ["8.8.8.8/24"], 
                    ip_deny_list = ["192.168.0.0/16"], 
                    active = True, 
                    active_since = '2025-02-12T08:41:44+05:30', 
                    auth_token = '72b378def0c1d83e6a015e654a744c380655565a68c591cf9f3598d0d14bdb5f', )
            )
        else:
            return ApiKeyResponse(
                data = workato_platform.client.workato_api.models.api_key.ApiKey(
                    id = 37326, 
                    name = 'Automation Inc.', 
                    auth_type = 'token', 
                    ip_allow_list = ["8.8.8.8/24"], 
                    ip_deny_list = ["192.168.0.0/16"], 
                    active = True, 
                    active_since = '2025-02-12T08:41:44+05:30', 
                    auth_token = '72b378def0c1d83e6a015e654a744c380655565a68c591cf9f3598d0d14bdb5f', ),
        )
        """

    def testApiKeyResponse(self):
        """Test ApiKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
