# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform_cli.client.workato_api.api.packages_api import PackagesApi


class TestPackagesApi(unittest.IsolatedAsyncioTestCase):
    """PackagesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PackagesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_download_package(self) -> None:
        """Test case for download_package

        Download package
        """
        pass

    async def test_export_package(self) -> None:
        """Test case for export_package

        Export a package based on a manifest
        """
        pass

    async def test_get_package(self) -> None:
        """Test case for get_package

        Get package details
        """
        pass

    async def test_import_package(self) -> None:
        """Test case for import_package

        Import a package into a folder
        """
        pass


if __name__ == '__main__':
    unittest.main()
