# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform_cli.client.workato_api.models.user import User

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()
        if include_optional:
            return User(
                id = 17293,
                name = 'ACME-API',
                created_at = '2019-06-19T19:53:16.886-07:00',
                plan_id = 'oem_plan',
                current_billing_period_start = '2020-09-22T19:15:11.372-07:00',
                current_billing_period_end = '2020-10-22T19:15:11.372-07:00',
                expert = False,
                avatar_url = 'https://workato-assets.s3.amazonaws.com/profiles/avatars/000/089/005/large/logo.png?1562399288',
                recipes_count = 49,
                interested_applications = [
                    ''
                    ],
                company_name = '',
                location = '',
                last_seen = '2020-08-23T23:22:24.329-07:00',
                contact_phone = '',
                contact_email = '',
                about_me = '',
                email = 'api-1@workato.com',
                phone = 'xxxxxxxxxx',
                active_recipes_count = 1,
                root_folder_id = 10294
            )
        else:
            return User(
                id = 17293,
                name = 'ACME-API',
                created_at = '2019-06-19T19:53:16.886-07:00',
                plan_id = 'oem_plan',
                current_billing_period_start = '2020-09-22T19:15:11.372-07:00',
                current_billing_period_end = '2020-10-22T19:15:11.372-07:00',
                recipes_count = 49,
                company_name = '',
                location = '',
                last_seen = '2020-08-23T23:22:24.329-07:00',
                email = 'api-1@workato.com',
                active_recipes_count = 1,
                root_folder_id = 10294,
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
