# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform_cli.client.workato_api.models.api_client_list_response import ApiClientListResponse

class TestApiClientListResponse(unittest.TestCase):
    """ApiClientListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiClientListResponse:
        """Test ApiClientListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiClientListResponse`
        """
        model = ApiClientListResponse()
        if include_optional:
            return ApiClientListResponse(
                data = [
                    workato_platform_cli.client.workato_api.models.api_client.ApiClient(
                        id = 1, 
                        name = 'Test client', 
                        description = '', 
                        active_api_keys_count = 2, 
                        total_api_keys_count = 2, 
                        created_at = '2023-05-25T08:08:21.413-07:00', 
                        updated_at = '2024-10-25T03:52:07.122-07:00', 
                        logo = 'https://s3-48296.alexv.awstf.workato.com/paperclip/api_customers/logos/000/000/001/small/psyduck.png?1729853526', 
                        logo_2x = 'https://s3-48296.alexv.awstf.workato.com/paperclip/api_customers/logos/000/000/001/medium/psyduck.png?1729853526', 
                        is_legacy = True, 
                        email = 'alex.das@workato.com', 
                        auth_type = 'token', 
                        api_token = '', 
                        mtls_enabled = True, 
                        validation_formula = 'OU=Workato', 
                        cert_bundle_ids = [3], 
                        api_policies = [
                            workato_platform_cli.client.workato_api.models.api_client_api_policies_inner.ApiClient_api_policies_inner(
                                id = 2, 
                                name = 'Internal – Admins', )
                            ], 
                        api_collections = [
                            workato_platform_cli.client.workato_api.models.api_client_api_collections_inner.ApiClient_api_collections_inner(
                                id = 1, 
                                name = 'Echo collection', )
                            ], )
                    ],
                count = 1,
                page = 1,
                per_page = 100
            )
        else:
            return ApiClientListResponse(
                data = [
                    workato_platform_cli.client.workato_api.models.api_client.ApiClient(
                        id = 1, 
                        name = 'Test client', 
                        description = '', 
                        active_api_keys_count = 2, 
                        total_api_keys_count = 2, 
                        created_at = '2023-05-25T08:08:21.413-07:00', 
                        updated_at = '2024-10-25T03:52:07.122-07:00', 
                        logo = 'https://s3-48296.alexv.awstf.workato.com/paperclip/api_customers/logos/000/000/001/small/psyduck.png?1729853526', 
                        logo_2x = 'https://s3-48296.alexv.awstf.workato.com/paperclip/api_customers/logos/000/000/001/medium/psyduck.png?1729853526', 
                        is_legacy = True, 
                        email = 'alex.das@workato.com', 
                        auth_type = 'token', 
                        api_token = '', 
                        mtls_enabled = True, 
                        validation_formula = 'OU=Workato', 
                        cert_bundle_ids = [3], 
                        api_policies = [
                            workato_platform_cli.client.workato_api.models.api_client_api_policies_inner.ApiClient_api_policies_inner(
                                id = 2, 
                                name = 'Internal – Admins', )
                            ], 
                        api_collections = [
                            workato_platform_cli.client.workato_api.models.api_client_api_collections_inner.ApiClient_api_collections_inner(
                                id = 1, 
                                name = 'Echo collection', )
                            ], )
                    ],
                count = 1,
                page = 1,
                per_page = 100,
        )
        """

    def testApiClientListResponse(self):
        """Test ApiClientListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
