# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform_cli.client.workato_api.api.connectors_api import ConnectorsApi


class TestConnectorsApi(unittest.IsolatedAsyncioTestCase):
    """ConnectorsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ConnectorsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_custom_connector_code(self) -> None:
        """Test case for get_custom_connector_code

        Get custom connector code
        """
        pass

    async def test_list_custom_connectors(self) -> None:
        """Test case for list_custom_connectors

        List custom connectors
        """
        pass

    async def test_list_platform_connectors(self) -> None:
        """Test case for list_platform_connectors

        List platform connectors
        """
        pass


if __name__ == '__main__':
    unittest.main()
