# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com`

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.custom_connector import CustomConnector

class TestCustomConnector(unittest.TestCase):
    """CustomConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomConnector:
        """Test CustomConnector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomConnector`
        """
        model = CustomConnector()
        if include_optional:
            return CustomConnector(
                id = 562523,
                name = 'apps_by_workato_connector_804586_1719241698',
                title = 'Apps by Workato',
                latest_released_version = 2,
                latest_released_version_note = 'Connector Version',
                released_versions = [
                    workato_platform.client.workato_api.models.connector_version.ConnectorVersion(
                        version = 2,
                        version_note = '',
                        created_at = '2024-06-24T11:17:52.516-04:00',
                        released_at = '2024-06-24T11:17:53.999-04:00', )
                    ],
                static_webhook_url = ''
            )
        else:
            return CustomConnector(
                id = 562523,
                name = 'apps_by_workato_connector_804586_1719241698',
                title = 'Apps by Workato',
                latest_released_version = 2,
                latest_released_version_note = 'Connector Version',
                released_versions = [
                    workato_platform.client.workato_api.models.connector_version.ConnectorVersion(
                        version = 2,
                        version_note = '',
                        created_at = '2024-06-24T11:17:52.516-04:00',
                        released_at = '2024-06-24T11:17:53.999-04:00', )
                    ],
                static_webhook_url = '',
        )
        """

    def testCustomConnector(self):
        """Test CustomConnector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
