# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.export_manifest_request import ExportManifestRequest

class TestExportManifestRequest(unittest.TestCase):
    """ExportManifestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExportManifestRequest:
        """Test ExportManifestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExportManifestRequest`
        """
        model = ExportManifestRequest()
        if include_optional:
            return ExportManifestRequest(
                name = 'Test Manifest',
                assets = [
                    workato_platform.client.workato_api.models.asset_reference.AssetReference(
                        id = 56, 
                        type = 'recipe', 
                        checked = True, 
                        version = 56, 
                        folder = '', 
                        absolute_path = '', 
                        root_folder = True, 
                        unreachable = True, 
                        zip_name = '', )
                    ],
                folder_id = 56,
                include_test_cases = True,
                auto_generate_assets = True,
                include_data = True,
                include_tags = True
            )
        else:
            return ExportManifestRequest(
                name = 'Test Manifest',
        )
        """

    def testExportManifestRequest(self):
        """Test ExportManifestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
