# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com`

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.recipe_connection_update_request import RecipeConnectionUpdateRequest

class TestRecipeConnectionUpdateRequest(unittest.TestCase):
    """RecipeConnectionUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecipeConnectionUpdateRequest:
        """Test RecipeConnectionUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecipeConnectionUpdateRequest`
        """
        model = RecipeConnectionUpdateRequest()
        if include_optional:
            return RecipeConnectionUpdateRequest(
                adapter_name = 'salesforce',
                connection_id = 772461
            )
        else:
            return RecipeConnectionUpdateRequest(
                adapter_name = 'salesforce',
                connection_id = 772461,
        )
        """

    def testRecipeConnectionUpdateRequest(self):
        """Test RecipeConnectionUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
