# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com`

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.recipe_config_inner import RecipeConfigInner

class TestRecipeConfigInner(unittest.TestCase):
    """RecipeConfigInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecipeConfigInner:
        """Test RecipeConfigInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecipeConfigInner`
        """
        model = RecipeConfigInner()
        if include_optional:
            return RecipeConfigInner(
                keyword = 'application',
                name = 'workato_service',
                provider = 'workato_service',
                skip_validation = False,
                account_id = 56
            )
        else:
            return RecipeConfigInner(
        )
        """

    def testRecipeConfigInner(self):
        """Test RecipeConfigInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
