# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.package_details_response_recipe_status_inner import PackageDetailsResponseRecipeStatusInner

class TestPackageDetailsResponseRecipeStatusInner(unittest.TestCase):
    """PackageDetailsResponseRecipeStatusInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageDetailsResponseRecipeStatusInner:
        """Test PackageDetailsResponseRecipeStatusInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageDetailsResponseRecipeStatusInner`
        """
        model = PackageDetailsResponseRecipeStatusInner()
        if include_optional:
            return PackageDetailsResponseRecipeStatusInner(
                id = 12345,
                import_result = 'no_update_or_updated_without_restart'
            )
        else:
            return PackageDetailsResponseRecipeStatusInner(
        )
        """

    def testPackageDetailsResponseRecipeStatusInner(self):
        """Test PackageDetailsResponseRecipeStatusInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
