# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com`

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.api_collection import ApiCollection

class TestApiCollection(unittest.TestCase):
    """ApiCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiCollection:
        """Test ApiCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiCollection`
        """
        model = ApiCollection()
        if include_optional:
            return ApiCollection(
                id = 1361,
                name = 'Quote to cash',
                project_id = '523144',
                url = 'https://api.peatql.io/quote-to-cash-v1',
                api_spec_url = 'https://www.workato.com/doc/service/quote-to-cash-v1/swagger?token={token}',
                version = '1.0',
                created_at = '2020-06-15T22:20:15.327-07:00',
                updated_at = '2020-06-15T22:20:15.327-07:00',
                message = 'Import completed successfully',
                import_results = workato_platform.client.workato_api.models.import_results.ImportResults(
                    success = True,
                    total_endpoints = 1,
                    failed_endpoints = 0,
                    failed_actions = [], )
            )
        else:
            return ApiCollection(
                id = 1361,
                name = 'Quote to cash',
                project_id = '523144',
                url = 'https://api.peatql.io/quote-to-cash-v1',
                api_spec_url = 'https://www.workato.com/doc/service/quote-to-cash-v1/swagger?token={token}',
                version = '1.0',
                created_at = '2020-06-15T22:20:15.327-07:00',
                updated_at = '2020-06-15T22:20:15.327-07:00',
        )
        """

    def testApiCollection(self):
        """Test ApiCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
