# coding: utf-8

"""
    Workato Platform API

    Official Workato Platform API for managing recipes, connections, projects, and other automation resources.  ## Authentication All endpoints require a Bearer token in the Authorization header.  ## Base URL The base URL varies by region: - US: `https://www.workato.com` - EU: `https://app.eu.workato.com` - JP: `https://app.jp.workato.com` - SG: `https://app.sg.workato.com` - AU: `https://app.au.workato.com` - IL: `https://app.il.workato.com` - Trial: `https://app.trial.workato.com`

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workato_platform.client.workato_api.models.picklist_response import PicklistResponse

class TestPicklistResponse(unittest.TestCase):
    """PicklistResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PicklistResponse:
        """Test PicklistResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PicklistResponse`
        """
        model = PicklistResponse()
        if include_optional:
            return PicklistResponse(
                data = [["Record ID","Id"],["Owner ID","OwnerId"],["Invoice Name","Name"],["Created Date","CreatedDate"],["Status","Status__c"]]
            )
        else:
            return PicklistResponse(
                data = [["Record ID","Id"],["Owner ID","OwnerId"],["Invoice Name","Name"],["Created Date","CreatedDate"],["Status","Status__c"]],
        )
        """

    def testPicklistResponse(self):
        """Test PicklistResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
