name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --group dev

    - name: Run ruff check
      run: uv run ruff check src/ tests/ --exclude src/workato_platform/client/

    - name: Run ruff format check
      run: uv run ruff format --check src/ tests/ --exclude src/workato_platform/client/

    - name: Run mypy
      run: uv run mypy src/ tests/
