name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --group dev

    - name: Run tests
      run: uv run pytest tests/ -v

    - name: Check coverage
      run: uv run coverage run -m pytest tests/ && uv run coverage report --fail-under=85
